imagePullPolicy: IfNotPresent
revisionHistoryLimit: 3
gitlabUrl: https://gitlab.com
terminationGracePeriodSeconds: 3600
concurrent: 3
checkInterval: 5
logLevel: debug
logFormat: json
sessionServer:
  enabled: false
rbac:
  create: true
  rules:
    - resources: ["pods", "secrets", "configmaps"]
      verbs: ["get", "list", "watch", "create",  "update",  "patch",  "delete"]
    - apiGroups: [""]
      resources:  ["pods/exec",  "pods/attach"]
      verbs: ["create", "patch", "delete"]
    - apiGroups: ["apps"]
      resources:  ["deployments"]
      verbs: ["get",  "list",  "watch",  "create",   "update",   "patch",   "delete"]
  
  clusterWideAccess: false
  podSecurityPolicy:
    enabled: false
    resourceNames:
      - gitlab-runner
metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false
service:
  enabled: false
runners:
  privileged: true
  config: |
    log_level = "debug"
    [[runners]]
      output_limit = 10000
      [runners.kubernetes]
        image = "ubuntu:22.04"
        # helper_image = "if use custom helper image"
  executor: kubernetes
  secret: runner-secret
podSecurityContext:
  runAsUser: 100
  fsGroup: 65533
resources:
  limits:
    memory: 2048Mi
    cpu: 2
  requests:
    memory: 1024Mi
    cpu: 1