apiVersion: v1
kind: Service
metadata:
  name: diplom-ffops8-site-service
  namespace: diplom-website
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30051